# Generated by Django 4.2.7 on 2024-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_gift_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
